// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/service.proto

package trackdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserTrack struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackId              string   `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTrack) Reset()         { *m = UserTrack{} }
func (m *UserTrack) String() string { return proto.CompactTextString(m) }
func (*UserTrack) ProtoMessage()    {}
func (*UserTrack) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_7c225b2112228ac4, []int{0}
}
func (m *UserTrack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTrack.Unmarshal(m, b)
}
func (m *UserTrack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTrack.Marshal(b, m, deterministic)
}
func (dst *UserTrack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTrack.Merge(dst, src)
}
func (m *UserTrack) XXX_Size() int {
	return xxx_messageInfo_UserTrack.Size(m)
}
func (m *UserTrack) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTrack.DiscardUnknown(m)
}

var xxx_messageInfo_UserTrack proto.InternalMessageInfo

func (m *UserTrack) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserTrack) GetTrackId() string {
	if m != nil {
		return m.TrackId
	}
	return ""
}

type TrackServerId struct {
	TrackServerId        string   `protobuf:"bytes,1,opt,name=track_server_id,json=trackServerId,proto3" json:"track_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackServerId) Reset()         { *m = TrackServerId{} }
func (m *TrackServerId) String() string { return proto.CompactTextString(m) }
func (*TrackServerId) ProtoMessage()    {}
func (*TrackServerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_7c225b2112228ac4, []int{1}
}
func (m *TrackServerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackServerId.Unmarshal(m, b)
}
func (m *TrackServerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackServerId.Marshal(b, m, deterministic)
}
func (dst *TrackServerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackServerId.Merge(dst, src)
}
func (m *TrackServerId) XXX_Size() int {
	return xxx_messageInfo_TrackServerId.Size(m)
}
func (m *TrackServerId) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackServerId.DiscardUnknown(m)
}

var xxx_messageInfo_TrackServerId proto.InternalMessageInfo

func (m *TrackServerId) GetTrackServerId() string {
	if m != nil {
		return m.TrackServerId
	}
	return ""
}

type TrackChunk struct {
	StartPosition        int32    `protobuf:"varint,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	NumBytes             int32    `protobuf:"varint,2,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackChunk) Reset()         { *m = TrackChunk{} }
func (m *TrackChunk) String() string { return proto.CompactTextString(m) }
func (*TrackChunk) ProtoMessage()    {}
func (*TrackChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_7c225b2112228ac4, []int{2}
}
func (m *TrackChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackChunk.Unmarshal(m, b)
}
func (m *TrackChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackChunk.Marshal(b, m, deterministic)
}
func (dst *TrackChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackChunk.Merge(dst, src)
}
func (m *TrackChunk) XXX_Size() int {
	return xxx_messageInfo_TrackChunk.Size(m)
}
func (m *TrackChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackChunk.DiscardUnknown(m)
}

var xxx_messageInfo_TrackChunk proto.InternalMessageInfo

func (m *TrackChunk) GetStartPosition() int32 {
	if m != nil {
		return m.StartPosition
	}
	return 0
}

func (m *TrackChunk) GetNumBytes() int32 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

func (m *TrackChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TrackUpload struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackUpload) Reset()         { *m = TrackUpload{} }
func (m *TrackUpload) String() string { return proto.CompactTextString(m) }
func (*TrackUpload) ProtoMessage()    {}
func (*TrackUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_7c225b2112228ac4, []int{3}
}
func (m *TrackUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackUpload.Unmarshal(m, b)
}
func (m *TrackUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackUpload.Marshal(b, m, deterministic)
}
func (dst *TrackUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackUpload.Merge(dst, src)
}
func (m *TrackUpload) XXX_Size() int {
	return xxx_messageInfo_TrackUpload.Size(m)
}
func (m *TrackUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackUpload.DiscardUnknown(m)
}

var xxx_messageInfo_TrackUpload proto.InternalMessageInfo

func (m *TrackUpload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrackUpload) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *TrackUpload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_7c225b2112228ac4, []int{4}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserTrack)(nil), "resonate.api.trackdata.UserTrack")
	proto.RegisterType((*TrackServerId)(nil), "resonate.api.trackdata.TrackServerId")
	proto.RegisterType((*TrackChunk)(nil), "resonate.api.trackdata.TrackChunk")
	proto.RegisterType((*TrackUpload)(nil), "resonate.api.trackdata.TrackUpload")
	proto.RegisterType((*Empty)(nil), "resonate.api.trackdata.Empty")
}

func init() { proto.RegisterFile("rpc/service.proto", fileDescriptor_service_7c225b2112228ac4) }

var fileDescriptor_service_7c225b2112228ac4 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4f, 0x32, 0x31,
	0x10, 0xce, 0xf2, 0xbe, 0x7c, 0xec, 0x20, 0xa2, 0x3d, 0x28, 0xe2, 0x05, 0xd7, 0x60, 0x38, 0xad,
	0x46, 0x0f, 0x1e, 0x4d, 0x50, 0x0f, 0x5c, 0x8c, 0x59, 0xe4, 0x42, 0x62, 0x48, 0xa1, 0x4d, 0xdc,
	0xe0, 0xb6, 0x4d, 0x3b, 0x4b, 0xc2, 0x8f, 0xf4, 0x3f, 0x99, 0xce, 0x22, 0x60, 0x82, 0xdc, 0x3a,
	0xf3, 0x7c, 0x6c, 0x9f, 0x67, 0x0b, 0xc7, 0xd6, 0xcc, 0xae, 0x9d, 0xb4, 0x8b, 0x74, 0x26, 0x63,
	0x63, 0x35, 0x6a, 0x76, 0x62, 0xa5, 0xd3, 0x8a, 0xa3, 0x8c, 0xb9, 0x49, 0x63, 0xb4, 0x7c, 0x36,
	0x17, 0x1c, 0x79, 0xf4, 0x00, 0xe1, 0xc8, 0x49, 0xfb, 0xe6, 0x17, 0xec, 0x14, 0xaa, 0xb9, 0x93,
	0x76, 0x92, 0x8a, 0x56, 0xd0, 0x09, 0x7a, 0x61, 0x52, 0xf1, 0xe3, 0x40, 0xb0, 0x33, 0xa8, 0x91,
	0xc4, 0x23, 0x25, 0x42, 0xaa, 0x34, 0x0f, 0x44, 0x74, 0x0f, 0x0d, 0x12, 0x0f, 0xa5, 0x5d, 0x10,
	0xf7, 0x0a, 0x9a, 0x05, 0xd7, 0xd1, 0x66, 0x63, 0xd6, 0xc0, 0x6d, 0x5e, 0x24, 0x00, 0x48, 0xf8,
	0xf8, 0x91, 0xab, 0x39, 0xeb, 0xc2, 0xa1, 0x43, 0x6e, 0x71, 0x62, 0xb4, 0x4b, 0x31, 0xd5, 0x8a,
	0x44, 0xe5, 0xa4, 0x41, 0xdb, 0xd7, 0xd5, 0x92, 0x9d, 0x43, 0xa8, 0xf2, 0x6c, 0x32, 0x5d, 0xa2,
	0x74, 0x74, 0x93, 0x72, 0x52, 0x53, 0x79, 0xd6, 0xf7, 0x33, 0x63, 0xf0, 0xdf, 0x67, 0x6a, 0xfd,
	0xeb, 0x04, 0xbd, 0x83, 0x84, 0xce, 0xd1, 0x0b, 0xd4, 0xe9, 0x2b, 0x23, 0xf3, 0xa9, 0xb9, 0xf0,
	0x14, 0xc5, 0x33, 0xb9, 0xba, 0x11, 0x9d, 0xb7, 0x53, 0x97, 0x7e, 0xa5, 0xde, 0xe5, 0x57, 0x85,
	0xf2, 0x73, 0x66, 0x70, 0x79, 0xfb, 0x15, 0xc0, 0x11, 0x39, 0x3f, 0x71, 0xe4, 0xc3, 0xa2, 0x6b,
	0x36, 0x86, 0xe6, 0x10, 0xad, 0xe4, 0xd9, 0x1a, 0x61, 0x17, 0xf1, 0xee, 0xe6, 0xe3, 0x75, 0xed,
	0xed, 0xe8, 0x2f, 0xca, 0xa6, 0x9f, 0x9b, 0x80, 0xbd, 0x43, 0xb3, 0x08, 0xb1, 0xf1, 0xbe, 0xdc,
	0x2b, 0x2c, 0xd8, 0xed, 0xee, 0x5e, 0xd2, 0xcf, 0xef, 0xe8, 0xd7, 0xc7, 0xe1, 0x1a, 0x9a, 0x56,
	0xe8, 0xd1, 0xdc, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xef, 0xc7, 0xf9, 0x49, 0x02, 0x00,
	0x00,
}
