// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/service.proto

package trackdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserTrack struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrackId              string   `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTrack) Reset()         { *m = UserTrack{} }
func (m *UserTrack) String() string { return proto.CompactTextString(m) }
func (*UserTrack) ProtoMessage()    {}
func (*UserTrack) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dc8d9397ebdb196, []int{0}
}
func (m *UserTrack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTrack.Unmarshal(m, b)
}
func (m *UserTrack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTrack.Marshal(b, m, deterministic)
}
func (dst *UserTrack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTrack.Merge(dst, src)
}
func (m *UserTrack) XXX_Size() int {
	return xxx_messageInfo_UserTrack.Size(m)
}
func (m *UserTrack) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTrack.DiscardUnknown(m)
}

var xxx_messageInfo_UserTrack proto.InternalMessageInfo

func (m *UserTrack) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserTrack) GetTrackId() string {
	if m != nil {
		return m.TrackId
	}
	return ""
}

type TrackServerId struct {
	TrackServerId        string   `protobuf:"bytes,1,opt,name=track_server_id,json=trackServerId,proto3" json:"track_server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackServerId) Reset()         { *m = TrackServerId{} }
func (m *TrackServerId) String() string { return proto.CompactTextString(m) }
func (*TrackServerId) ProtoMessage()    {}
func (*TrackServerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dc8d9397ebdb196, []int{1}
}
func (m *TrackServerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackServerId.Unmarshal(m, b)
}
func (m *TrackServerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackServerId.Marshal(b, m, deterministic)
}
func (dst *TrackServerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackServerId.Merge(dst, src)
}
func (m *TrackServerId) XXX_Size() int {
	return xxx_messageInfo_TrackServerId.Size(m)
}
func (m *TrackServerId) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackServerId.DiscardUnknown(m)
}

var xxx_messageInfo_TrackServerId proto.InternalMessageInfo

func (m *TrackServerId) GetTrackServerId() string {
	if m != nil {
		return m.TrackServerId
	}
	return ""
}

type TrackChunk struct {
	StartPosition        int32    `protobuf:"varint,1,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
	NumBytes             int32    `protobuf:"varint,2,opt,name=num_bytes,json=numBytes,proto3" json:"num_bytes,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackChunk) Reset()         { *m = TrackChunk{} }
func (m *TrackChunk) String() string { return proto.CompactTextString(m) }
func (*TrackChunk) ProtoMessage()    {}
func (*TrackChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dc8d9397ebdb196, []int{2}
}
func (m *TrackChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackChunk.Unmarshal(m, b)
}
func (m *TrackChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackChunk.Marshal(b, m, deterministic)
}
func (dst *TrackChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackChunk.Merge(dst, src)
}
func (m *TrackChunk) XXX_Size() int {
	return xxx_messageInfo_TrackChunk.Size(m)
}
func (m *TrackChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackChunk.DiscardUnknown(m)
}

var xxx_messageInfo_TrackChunk proto.InternalMessageInfo

func (m *TrackChunk) GetStartPosition() int32 {
	if m != nil {
		return m.StartPosition
	}
	return 0
}

func (m *TrackChunk) GetNumBytes() int32 {
	if m != nil {
		return m.NumBytes
	}
	return 0
}

func (m *TrackChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dc8d9397ebdb196, []int{3}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UserTrack)(nil), "resonate.api.trackdata.UserTrack")
	proto.RegisterType((*TrackServerId)(nil), "resonate.api.trackdata.TrackServerId")
	proto.RegisterType((*TrackChunk)(nil), "resonate.api.trackdata.TrackChunk")
	proto.RegisterType((*Empty)(nil), "resonate.api.trackdata.Empty")
}

func init() { proto.RegisterFile("rpc/service.proto", fileDescriptor_service_5dc8d9397ebdb196) }

var fileDescriptor_service_5dc8d9397ebdb196 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0x96, 0xdf, 0x97, 0x7e, 0xe4, 0xa0, 0x04, 0x3c, 0x40, 0x29, 0x4b, 0x89, 0x54, 0x94, 0x29,
	0x20, 0x18, 0x18, 0x91, 0x0a, 0x0c, 0xdd, 0x50, 0x42, 0x97, 0x0e, 0x44, 0x6e, 0x6c, 0x89, 0xa8,
	0x24, 0xb6, 0xec, 0x4b, 0xa5, 0xfe, 0x49, 0x7e, 0x13, 0xca, 0x15, 0x12, 0x06, 0x40, 0x6c, 0x7e,
	0xbe, 0xce, 0xbe, 0xc7, 0x70, 0x68, 0x4d, 0x76, 0xe1, 0x94, 0x5d, 0xe7, 0x99, 0x8a, 0x8c, 0xd5,
	0xa8, 0xf9, 0x91, 0x55, 0x4e, 0x97, 0x02, 0x55, 0x24, 0x4c, 0x1e, 0xa1, 0x15, 0xd9, 0x4a, 0x0a,
	0x14, 0xc1, 0x2d, 0x78, 0x73, 0xa7, 0xec, 0x53, 0x4d, 0xf0, 0x63, 0xe8, 0x55, 0x4e, 0xd9, 0x34,
	0x97, 0x43, 0x36, 0x66, 0xa1, 0x17, 0x77, 0x6b, 0x38, 0x93, 0xfc, 0x04, 0xfa, 0x14, 0xa9, 0x95,
	0x7f, 0xa4, 0xf4, 0x08, 0xcf, 0x64, 0x70, 0x03, 0x03, 0x0a, 0x27, 0xca, 0xae, 0xc9, 0x7b, 0x0e,
	0xfe, 0xd6, 0xeb, 0x88, 0x69, 0x87, 0x0d, 0xf0, 0xab, 0x2f, 0x90, 0x00, 0x14, 0xbc, 0x7b, 0xa9,
	0xca, 0x15, 0x9f, 0xc0, 0xbe, 0x43, 0x61, 0x31, 0x35, 0xda, 0xe5, 0x98, 0xeb, 0x92, 0x42, 0x9d,
	0x78, 0x40, 0xec, 0xe3, 0x07, 0xc9, 0x4f, 0xc1, 0x2b, 0xab, 0x22, 0x5d, 0x6e, 0x50, 0x39, 0x7a,
	0x49, 0x27, 0xee, 0x97, 0x55, 0x31, 0xad, 0x31, 0xe7, 0xb0, 0x53, 0xef, 0x34, 0xfc, 0x3f, 0x66,
	0xe1, 0x5e, 0x4c, 0xe7, 0xa0, 0x07, 0x9d, 0x87, 0xc2, 0xe0, 0xe6, 0xea, 0x8d, 0xc1, 0x01, 0xdd,
	0x77, 0x2f, 0x50, 0x24, 0xdb, 0x6e, 0xf8, 0x02, 0xfc, 0x04, 0xad, 0x12, 0x45, 0xa3, 0xf0, 0xb3,
	0xe8, 0xfb, 0xa6, 0xa2, 0xa6, 0xa6, 0x51, 0xf0, 0x93, 0xa5, 0xdd, 0xe7, 0x92, 0xf1, 0x67, 0xf0,
	0xe7, 0xe6, 0x55, 0x0b, 0xd9, 0xce, 0xfe, 0x43, 0x70, 0x34, 0xf9, 0xd5, 0xf3, 0xd9, 0x5e, 0xc8,
	0xa6, 0xbb, 0x0b, 0xaf, 0x11, 0x97, 0x5d, 0xfa, 0xe5, 0xeb, 0xf7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x4b, 0x2f, 0x77, 0x24, 0xfa, 0x01, 0x00, 0x00,
}
